{
  "acknowledgement": "\nRed Hat would like to thank the OpenStack project for reporting this issue. Upstream acknowledges Thomas Leaman of HP as the original reporter.\n    ",
  "affected_release": {
    "advisory": "RHSA-2013:1200",
    "cpe": "cpe:/a:redhat:openstack:3::el6",
    "package": "python-glanceclient-1:0.9.0-2.el6ost",
    "product_name": "Red Hat Enterprise Linux OpenStack Platform 3.0",
    "release_date": "2013-09-03T00:00:00"
  },
  "bugzilla": {
    "description": "\nCVE-2013-4111 OpenStack: python-glanceclient failing SSL certificate check\n    ",
    "id": "989738",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=989738"
  },
  "cvss": {
    "cvss_base_score": "5.0",
    "cvss_scoring_vector": "AV:N/AC:L/Au:N/C:N/I:P/A:N",
    "status": "verified"
  },
  "cwe": "CWE-295",
  "details": [
    "\nThe Python client library for Glance (python-glanceclient) before 0.10.0 does not properly check the preverify_ok value, which prevents the server hostname from being verified with a domain name in the subject's Common Name (CN) or subjectAltName field of the X.509 certificate and allows man-in-the-middle attackers to spoof SSL servers via an arbitrary valid certificate.\n    "
  ],
  "name": "CVE-2013-4111",
  "package_state": {
    "cpe": "cpe:/a:redhat:openstack:4",
    "fix_state": "Will not fix",
    "package_name": "python-glanceclient",
    "product_name": "Red Hat Enterprise Linux OpenStack Platform 4.0"
  },
  "public_date": "2013-07-29T00:00:00",
  "statement": "\nRed Hat Enterprise Linux OpenStack Platform 4.0: \nThis vulnerability has been rated as having a security impact of Moderate. After evaluation and in accordance with the criteria noted in the product support life cycle, there are no plans to address this issue in an upcoming release. Please contact Red Hat Support for further information.\n    ",
  "threat_severity": "Moderate"
}