{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2019-9674"
    },
    "affects": {
      "vendor": {
        "vendor_data": []
      }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Lib/zipfile.py in Python through 3.7.2 allows remote attackers to cause a denial of service (resource consumption) via a ZIP bomb."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://bugs.python.org/issue36260",
          "refsource": "MISC",
          "tags": [],
          "url": "https://bugs.python.org/issue36260"
        },
        {
          "name": "https://bugs.python.org/issue36462",
          "refsource": "MISC",
          "tags": [],
          "url": "https://bugs.python.org/issue36462"
        },
        {
          "name": "https://github.com/python/cpython/blob/master/Lib/zipfile.py",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/python/cpython/blob/master/Lib/zipfile.py"
        },
        {
          "name": "https://python-security.readthedocs.io/security.html#archives-and-zip-bomb",
          "refsource": "MISC",
          "tags": [],
          "url": "https://python-security.readthedocs.io/security.html#archives-and-zip-bomb"
        },
        {
          "name": "https://www.python.org/news/security/",
          "refsource": "MISC",
          "tags": [],
          "url": "https://www.python.org/news/security/"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2020-02-04T16:28Z",
  "publishedDate": "2020-02-04T15:15Z"
}