{
  "bugzilla": {
    "description": "\nCVE-2019-16249 opencv: Out-of-bounds read in hal_baseline::v_load in core/hal/intrin_sse.hpp\n    ",
    "id": "1752702",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1752702"
  },
  "cvss3": {
    "cvss3_base_score": "4.7",
    "cvss3_scoring_vector": "CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:N/A:N",
    "status": "draft"
  },
  "cwe": "CWE-125",
  "details": [
    "\nOpenCV 4.1.1 has an out-of-bounds read in hal_baseline::v_load in core/hal/intrin_sse.hpp when called from computeSSDMeanNorm in modules/video/src/dis_flow.cpp.\n    "
  ],
  "name": "CVE-2019-16249",
  "package_state": [
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:6",
      "fix_state": "New",
      "package_name": "opencv",
      "product_name": "Red Hat Enterprise Linux 6"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:7",
      "fix_state": "New",
      "package_name": "opencv",
      "product_name": "Red Hat Enterprise Linux 7"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:8",
      "fix_state": "New",
      "package_name": "opencv",
      "product_name": "Red Hat Enterprise Linux 8"
    }
  ],
  "public_date": "2019-09-08T00:00:00",
  "threat_severity": "Low"
}