{
  "bugzilla": {
    "description": "\nCVE-2019-9740 python: improper neutralization of CRLF sequences in urllib module\n    ",
    "id": "1688169",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1688169"
  },
  "cvss3": {
    "cvss3_base_score": "6.5",
    "cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
    "status": "draft"
  },
  "cwe": "CWE-113",
  "details": [
    "\nAn issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.2. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n followed by an HTTP header or a Redis command.\n    "
  ],
  "name": "CVE-2019-9740",
  "package_state": [
    {
      "cpe": "cpe:/a:redhat:rhel_software_collections:3",
      "fix_state": "Affected",
      "package_name": "python27-python",
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux"
    },
    {
      "cpe": "cpe:/a:redhat:rhel_software_collections:3",
      "fix_state": "Affected",
      "package_name": "rh-python35-python",
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux"
    },
    {
      "cpe": "cpe:/a:redhat:rhel_software_collections:3",
      "fix_state": "Affected",
      "package_name": "rh-python36-python",
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux"
    },
    {
      "cpe": "cpe:/a:redhat:rhev_manager:4",
      "fix_state": "New",
      "package_name": "redhat-virtualization-host",
      "product_name": "Red Hat Virtualization 4"
    },
    {
      "cpe": "cpe:/a:redhat:rhev_manager:4",
      "fix_state": "New",
      "package_name": "rhvm-appliance",
      "product_name": "Red Hat Virtualization 4"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:5",
      "fix_state": "Will not fix",
      "package_name": "python",
      "product_name": "Red Hat Enterprise Linux 5"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:6",
      "fix_state": "Will not fix",
      "package_name": "python",
      "product_name": "Red Hat Enterprise Linux 6"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:7",
      "fix_state": "Affected",
      "package_name": "python3",
      "product_name": "Red Hat Enterprise Linux 7"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:7",
      "fix_state": "Affected",
      "package_name": "python",
      "product_name": "Red Hat Enterprise Linux 7"
    }
  ],
  "public_date": "2019-03-13T00:00:00",
  "statement": "\nThis issue affects:\n* All current versions of Red Hat OpenStack Platform. However, version 8 is due to retire on the 20th of April 2019, there are no more planned releases prior to this date.\n    ",
  "threat_severity": "Moderate"
}