{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat OpenStack Platform 13 (Queens)",
      "fix_state": "Will not fix",
      "package_name": "numpy",
      "cpe": "cpe:/a:redhat:openstack:13"
    },
    {
      "product_name": "Red Hat OpenStack Platform 14 (Rocky)",
      "fix_state": "Will not fix",
      "package_name": "numpy",
      "cpe": "cpe:/a:redhat:openstack:14"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Affected",
      "package_name": "rh-python36-numpy",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Affected",
      "package_name": "rh-python35-numpy",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Affected",
      "package_name": "python27-numpy",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Will not fix",
      "package_name": "numpy",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Affected",
      "package_name": "numpy",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "numpy",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "python27:2.7/numpy",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Virtualization 4",
      "fix_state": "Fix deferred",
      "package_name": "rhvm-appliance",
      "cpe": "cpe:/:redhat:enterprise_linux:::hypervisor"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2019-01-16T00:00:00Z",
  "bugzilla": {
    "description": "\nCVE-2019-6446 numpy: crafted serialized object passed in numpy.load() in pickle python module allows arbitrary code execution\n    ",
    "id": "1667950",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1667950"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "8.8",
    "cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-358-\u003eCWE-20",
  "statement": "\n\n    ",
  "acknowledgement": "",
  "name": "CVE-2019-6446",
  "document_distribution": "",
  "details": [
    "\n** DISPUTED **   An issue was discovered in NumPy 1.16.0 and earlier. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call. NOTE: third parties dispute this issue because it is  a behavior that might have legitimate applications in (for example)  loading serialized Python object arrays from trusted and authenticated  sources.\n    "
  ],
  "references": null
}