{
  "bugzilla": {
    "description": "\nCVE-2016-5032 libdwarf: Out-of-bounds read in dwarf_get_xu_hash_entry()\n    ",
    "id": "1340087",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1340087"
  },
  "cvss": {
    "cvss_base_score": "1.7",
    "cvss_scoring_vector": "AV:L/AC:L/Au:S/C:N/I:N/A:P",
    "status": "draft"
  },
  "cwe": "CWE-125",
  "details": [
    "\nThe dwarf_get_xu_hash_entry function in libdwarf before 20160923 allows remote attackers to cause a denial of service (crash) via a crafted file.\n    "
  ],
  "name": "CVE-2016-5032",
  "package_state": {
    "cpe": "cpe:/o:redhat:enterprise_linux:7",
    "fix_state": "Will not fix",
    "package_name": "libdwarf",
    "product_name": "Red Hat Enterprise Linux 7"
  },
  "public_date": "2016-05-18T00:00:00",
  "references": [
    "\nhttps://www.prevanders.net/dwarfbug.html\n    "
  ],
  "threat_severity": "Low"
}