{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Ceph Storage 1.3",
      "fix_state": "Not affected",
      "package_name": "Django",
      "cpe": "cpe:/a:redhat:ceph_storage:1.3"
    },
    {
      "product_name": "Red Hat Ceph Storage 2",
      "fix_state": "Not affected",
      "package_name": "Django",
      "cpe": "cpe:/a:redhat:ceph_storage:2"
    },
    {
      "product_name": "Red Hat OpenStack Platform 10.0 Operational Tools for RHEL 7",
      "fix_state": "Not affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:openstack-optools:10"
    },
    {
      "product_name": "Red Hat Enterprise Linux OpenStack Platform 7.0 Operational Tools for RHEL 7",
      "fix_state": "Not affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:openstack-optools:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux OpenStack Platform 8.0 Operational Tools for RHEL 7",
      "fix_state": "Not affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:openstack-optools:8"
    },
    {
      "product_name": "Red Hat OpenStack Platform 9.0 Operational Tools for RHEL 7",
      "fix_state": "Not affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:openstack-optools:9"
    },
    {
      "product_name": "Red Hat OpenStack Platform 10",
      "fix_state": "Not affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:openstack:10"
    },
    {
      "product_name": "Red Hat Enterprise Linux OpenStack Platform 5.0 (Icehouse)",
      "fix_state": "Not affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:openstack:5"
    },
    {
      "product_name": "Red Hat Enterprise Linux OpenStack Platform 6.0 (Juno) for RHEL 7",
      "fix_state": "Not affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:openstack:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux OpenStack Platform 7.0 (Kilo) for RHEL 7",
      "fix_state": "Not affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:openstack:7"
    },
    {
      "product_name": "Red Hat OpenStack Platform 8.0 (Liberty)",
      "fix_state": "Not affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:openstack:8"
    },
    {
      "product_name": "Red Hat OpenStack Platform 9.0",
      "fix_state": "Not affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:openstack:9"
    },
    {
      "product_name": "Red Hat Subscription Asset Manager 1",
      "fix_state": "Will not fix",
      "package_name": "Django",
      "cpe": "cpe:/a:redhat:rhel_sam:1"
    },
    {
      "product_name": "Red Hat Storage Console 2",
      "fix_state": "Not affected",
      "package_name": "Django",
      "cpe": "cpe:/a:redhat:rhscon:2"
    },
    {
      "product_name": "Red Hat Storage Console 2",
      "fix_state": "Not affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:rhscon:2"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2016-11-01T00:00:00Z",
  "bugzilla": {
    "description": "\nCVE-2016-9013 python-django: user with hardcoded password created when running tests on Oracle\n    ",
    "id": "1389414",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1389414"
  },
  "cvss": {
    "cvss_base_score": "4.0",
    "cvss_scoring_vector": "AV:N/AC:H/Au:N/C:P/I:P/A:N",
    "status": "draft"
  },
  "cvss3": {
    "cvss3_base_score": "7.4",
    "cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-798",
  "statement": "\nRed Hat Subscription Asset Manager 1: \nThis vulnerability has been rated as having a security impact of Moderate. After evaluation and in accordance with the criteria noted in the product support life cycle, there are no plans to address this issue in an upcoming release. Please contact Red Hat Support for further information.\n    ",
  "acknowledgement": "\nRed Hat would like to thank the Django project for reporting this issue.\n    ",
  "name": "CVE-2016-9013",
  "document_distribution": "",
  "details": [
    "\nDjango 1.8.x before 1.8.16, 1.9.x before 1.9.11, and 1.10.x before 1.10.3 use a hardcoded password for a temporary database user created when running tests with an Oracle database, which makes it easier for remote attackers to obtain access to the database server by leveraging failure to manually specify a password in the database settings TEST dictionary.\n    "
  ],
  "references": null
}