{
  "affected_release": [
    {
      "product_name": "Red Hat Enterprise Linux OpenStack Platform 5.0 (Icehouse) for RHEL 6",
      "release_date": "2016-03-24T00:00:00Z",
      "advisory": "RHSA-2016:0502",
      "package": "python-django-1.6.11-5.el6ost",
      "cpe": "cpe:/a:redhat:openstack:5::el6"
    },
    {
      "product_name": "Red Hat Enterprise Linux OpenStack Platform 5.0 (Icehouse) for RHEL 7",
      "release_date": "2016-03-24T00:00:00Z",
      "advisory": "RHSA-2016:0506",
      "package": "python-django-1.6.11-5.el7ost",
      "cpe": "cpe:/a:redhat:openstack:5::el7"
    },
    {
      "product_name": "Red Hat Enterprise Linux OpenStack Platform 6.0 (Juno) for RHEL 7",
      "release_date": "2016-03-24T00:00:00Z",
      "advisory": "RHSA-2016:0505",
      "package": "python-django-1.6.11-5.el7ost",
      "cpe": "cpe:/a:redhat:openstack:6::el7"
    },
    {
      "product_name": "Red Hat Enterprise Linux OpenStack Platform 7.0 (Kilo) for RHEL 7",
      "release_date": "2016-03-24T00:00:00Z",
      "advisory": "RHSA-2016:0504",
      "package": "python-django-1.8.11-1.el7ost",
      "cpe": "cpe:/a:redhat:openstack:7::el7"
    },
    {
      "product_name": "Red Hat Enterprise Linux OpenStack Platform 7.0 Operational Tools for RHEL 7",
      "release_date": "2016-03-24T00:00:00Z",
      "advisory": "RHSA-2016:0503",
      "package": "python-django-1.6.11-5.el7ost",
      "cpe": "cpe:/a:redhat:openstack-optools:7::el7"
    }
  ],
  "package_state": [
    {
      "product_name": "Red Hat Ceph Storage 1.2",
      "fix_state": "Will not fix",
      "package_name": "Django",
      "cpe": "cpe:/a:redhat:ceph_storage:1.2"
    },
    {
      "product_name": "Red Hat Ceph Storage 1.3",
      "fix_state": "Will not fix",
      "package_name": "Django",
      "cpe": "cpe:/a:redhat:ceph_storage:1.3"
    },
    {
      "product_name": "Red Hat Enterprise Linux OpenStack Platform 8.0 Operational Tools for RHEL 7",
      "fix_state": "Not affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:openstack-optools:8"
    },
    {
      "product_name": "Red Hat OpenStack Platform 8.0 (Liberty)",
      "fix_state": "Not affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:openstack:8"
    },
    {
      "product_name": "Red Hat Subscription Asset Manager 1",
      "fix_state": "Will not fix",
      "package_name": "Django",
      "cpe": "cpe:/a:redhat:rhel_sam:1"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2016-03-01T00:00:00Z",
  "bugzilla": {
    "description": "\nCVE-2016-2512 python-django: Malicious redirect and possible XSS attack via user-supplied redirect URLs containing basic auth\n    ",
    "id": "1311431",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1311431"
  },
  "cvss": {
    "cvss_base_score": "5.8",
    "cvss_scoring_vector": "AV:N/AC:M/Au:N/C:P/I:P/A:N",
    "status": "verified"
  },
  "cvss3": {
    "cvss3_base_score": "",
    "cvss3_scoring_vector": "",
    "status": ""
  },
  "iava": "",
  "cwe": "CWE-601",
  "statement": "\nRed Hat Ceph Storage 1.2: \nThis vulnerability has been rated as having a security impact of Moderate. After evaluation and in accordance with the criteria noted in the product support life cycle, there are no plans to address this issue in an upcoming release. Please contact Red Hat Support for further information.\n\nRed Hat Ceph Storage 1.3: \nThis vulnerability has been rated as having a security impact of Moderate. After evaluation and in accordance with the criteria noted in the product support life cycle, there are no plans to address this issue in an upcoming release. Please contact Red Hat Support for further information.\n\nRed Hat Subscription Asset Manager 1: \nThis vulnerability has been rated as having a security impact of Moderate. After evaluation and in accordance with the criteria noted in the product support life cycle, there are no plans to address this issue in an upcoming release. Please contact Red Hat Support for further information.\n    ",
  "acknowledgement": "\nRed Hat would like to thank the Django project for reporting this issue.\n    ",
  "name": "CVE-2016-2512",
  "document_distribution": "",
  "details": [
    "\nThe utils.http.is_safe_url function in Django before 1.8.10 and 1.9.x before 1.9.3 allows remote attackers to redirect users to arbitrary web sites and conduct phishing attacks or possibly conduct cross-site scripting (XSS) attacks via a URL containing basic authentication, as demonstrated by http://mysite.example.com\\@attacker.com.\n    ",
    "\nAn open-redirect flaw was found in the way Django's django.utils.http.is_safe_url() function filtered authentication URLs. An attacker able to trick a victim into visiting a crafted URL could use this flaw to redirect that victim to a malicious site.\n    "
  ],
  "references": [
    "\nhttps://www.djangoproject.com/weblog/2016/mar/01/security-releases/\n    "
  ]
}