{
  "description": "An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered\u003ccv::HaarEvaluator\u003e in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service.",
  "releases": {
    "bullseye": {
      "repositories": {
        "bullseye": "3.2.0+dfsg-6"
      },
      "status": "open",
      "urgency": "medium**"
    },
    "buster": {
      "repositories": {
        "buster": "3.2.0+dfsg-6"
      },
      "status": "open",
      "urgency": "medium**"
    },
    "jessie": {
      "nodsa": "Minor issue, DoS, PoC not crashing",
      "nodsa_reason": "postponed",
      "repositories": {
        "jessie": "2.4.9.1+dfsg-1+deb8u1",
        "jessie-security": "2.4.9.1+dfsg-1+deb8u2"
      },
      "status": "open",
      "urgency": "medium**"
    },
    "sid": {
      "repositories": {
        "sid": "3.2.0+dfsg-6"
      },
      "status": "open",
      "urgency": "medium**"
    },
    "stretch": {
      "repositories": {
        "stretch": "2.4.9.1+dfsg1-2"
      },
      "status": "open",
      "urgency": "medium**"
    }
  },
  "scope": "remote"
}