{
  "bugzilla": {
    "description": "\nCVE-2018-5735 bind: Assertion failure in validator.c due to incorrect handling of DNSSEC validation\n    ",
    "id": "1551511",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1551511"
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "cwe": "CWE-617",
  "details": [
    "\n** RESERVED ** This candidate has been reserved by an organization or individual that will use it when announcing a new security problem.  When the candidate has been publicized, the details for this candidate will be provided.\n    "
  ],
  "name": "CVE-2018-5735",
  "package_state": [
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:5",
      "fix_state": "Not affected",
      "package_name": "bind97",
      "product_name": "Red Hat Enterprise Linux 5"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:5",
      "fix_state": "Not affected",
      "package_name": "bind",
      "product_name": "Red Hat Enterprise Linux 5"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:6",
      "fix_state": "Not affected",
      "package_name": "bind",
      "product_name": "Red Hat Enterprise Linux 6"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:7",
      "fix_state": "Not affected",
      "package_name": "bind",
      "product_name": "Red Hat Enterprise Linux 7"
    }
  ],
  "public_date": "2018-02-19T00:00:00",
  "statement": "\nThis issue is the same as CVE-2017-3139. For more information, refer to CVE-2017-3139.\n    ",
  "threat_severity": "Important"
}