{
  "bugzilla": {
    "description": "\nCVE-2014-1624 pyxdg: TOCTOU race condition in get_runtime_dir() when strict=False\n    ",
    "id": "1056338",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1056338"
  },
  "cvss": {
    "cvss_base_score": "3.3",
    "cvss_scoring_vector": "AV:L/AC:M/Au:N/C:P/I:P/A:N",
    "status": "draft"
  },
  "cwe": "CWE-367",
  "details": [
    "\nRace condition in the xdg.BaseDirectory.get_runtime_dir function in python-xdg 0.25 allows local users to overwrite arbitrary files by pre-creating /tmp/pyxdg-runtime-dir-fallback-victim to point to a victim-owned location, then replacing it with a symlink to an attacker-controlled location once the get_runtime_dir function is called.\n    "
  ],
  "name": "CVE-2014-1624",
  "package_state": [
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:6",
      "fix_state": "Not affected",
      "package_name": "pyxdg",
      "product_name": "Red Hat Enterprise Linux 6"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:7",
      "fix_state": "Not affected",
      "package_name": "pyxdg",
      "product_name": "Red Hat Enterprise Linux 7"
    }
  ],
  "public_date": "2014-01-21T00:00:00",
  "threat_severity": "Moderate"
}